# Generated by Django 3.1.4 on 2020-12-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_book_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
