# Generated by Django 3.1.4 on 2020-12-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_auto_20201221_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.TextField(verbose_name='Название издательства')),
                ('foundation_year', models.SmallIntegerField(verbose_name='Дата основания')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(to='p_library.Publisher', verbose_name='Издательство'),
        ),
    ]
