# Generated by Django 3.1.4 on 2020-12-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0009_auto_20201222_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
