# Generated by Django 3.1.4 on 2020-12-22 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0011_book_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPublishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookpublishing_book', to='p_library.book', verbose_name='Книга')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookpublishing_publisher', to='p_library.publisher', verbose_name='Издательство')),
            ],
        ),
    ]
