# Generated by Django 3.1.4 on 2020-12-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0012_bookpublishing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookPublishing',
        ),
    ]
